name = "willinwang-pageviews"
type = "javascript"
workers_dev = true
compatibility_date = "2021-12-29"
account_id = "d80bb76f219708c3eed13ab64d767594"

[env.production]
workers_dev = false
zone_id = "27f380ccfeb8fe91c829111102329afb"
route = "pageviews.edui123.com/*"
kv_namespaces = [
         { binding = "VIEWS", id = "32b30482817a494fa84852f123b26103" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
